name: Deploy Mainnet

on:
  push:
    branches:
      - stable

concurrency:
  group: 'near-wallet-stable'
  cancel-in-progress: true

jobs:
  deploy-testnet:
    uses: ./.github/workflows/bundle-and-deploy.yml
    with:
      environment: mainnet
      near_wallet_env: mainnet
    secrets: inherit
